version: "3.8"

services:
  cups:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ADMIN_USER=admin
        - ADMIN_PASS=cupsadmin
    ports:
      - "631:631" 
      - "9100:9100" 
    # volumes:
    #   - ./cups-config:/etc/cups 
