#!/bin/bash

convert safari-pinned-tab.png -resize 120x120 apple-icon-120x120.png
convert safari-pinned-tab.png -resize 152x152 apple-icon-152x152.png
convert safari-pinned-tab.png -resize 167x167 apple-icon-167x167.png
convert safari-pinned-tab.png -resize 180x180 apple-icon-180x180.png
convert safari-pinned-tab.png -resize 512x512 apple-icon-512x512.png
convert safari-pinned-tab.png -resize 152x152 apple-touch-icon.png
convert safari-pinned-tab.png -resize 128x128 favicon-128x128.png
convert safari-pinned-tab.png -resize 16x16 favicon-16x16.png
convert safari-pinned-tab.png -resize 32x32 favicon-32x32.png
convert safari-pinned-tab.png -resize 512x512 favicon-512x512.png
convert safari-pinned-tab.png -resize 96x96 favicon-96x96.png
convert safari-pinned-tab.png -resize 1240x1240 icon-1240x1240.png
convert safari-pinned-tab.png -resize 128x128 icon-128x128.png
convert safari-pinned-tab.png -resize 192x192 icon-192x192.png
convert safari-pinned-tab.png -resize 256x256 icon-256x256.png
convert safari-pinned-tab.png -resize 384x384 icon-384x384.png
convert safari-pinned-tab.png -resize 512x512 icon-512x512.png
convert safari-pinned-tab.png -resize 144x144 ms-icon-144x144.png
convert safari-pinned-tab.png -resize 150x150 mstile-150x150.png
